pipeline {
    agent any
    tools {
        jdk 'JDK21'
        maven 'Maven3'
    }
    stages {
        stage('Build') {
            steps{
                    bat 'mvn -Dmaven.test.failure.ignore=true clean package'
                }
            }
        stage('Docker Build') {
            steps {
                bat 'docker build -t bnuthana20-prog/my-jenkins-app:${BUILD_NUMBER} .'
            }
        }
    }
}
